### ISSUE TITLE
Failed at the angular2-google-recaptcha@1.0.3 postinstall script 'typings install'.

### ISSUE THREAD

**Issue by wildAstroboy** [rajan-g/angular2-google-recaptcha#9]
npm install for this package fails at typings install.

verbose stack Error: angular2-google-recaptcha@1.0.3 postinstall: `typings install`
243 verbose stack spawn ENOENT
243 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
243 verbose stack     at emitTwo (events.js:106:13)
243 verbose stack     at ChildProcess.emit (events.js:191:7)
243 verbose stack     at maybeClose (internal/child_process.js:886:16)
243 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
244 verbose pkgid angular2-google-recaptcha@1.0.3
245 verbose cwd /Users/Samir/Desktop/portfolio-app/my-resume
246 verbose Darwin 16.6.0
247 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "angular2-google-recaptcha"
248 verbose node v6.10.2
249 verbose npm  v5.0.3
250 error file sh
251 error code ELIFECYCLE
252 error errno ENOENT
253 error syscall spawn
254 error angular2-google-recaptcha@1.0.3 postinstall: `typings install`
254 error spawn ENOENT
255 error Failed at the angular2-google-recaptcha@1.0.3 postinstall script.
255 error This is probably not a problem with npm. There is likely additional logging output above.
256 verbose exit [ 1, true ]

**Comment by jack-bliss** [comment]
i had this, ran `npm i -g typings` and then reinstalled the library and it seemed to install after that.
